pipeline:
  name: my-first-pipeline
  identifier: myfirstpipeline
  projectIdentifier: myfirstci
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: first_git
        repoName: Smallest-spring-boot-sample
        build: <+input>
  stages:
    - stage:
        name: Build
        identifier: Build
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: false
            override: false
            paths: []
          buildIntelligence:
            enabled: false
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Run Tests
                  identifier: Run_Tests
                  spec:
                    connectorRef: first_Docker
                    image: maven:3.9.6-eclipse-temurin-17
                    shell: Bash
                    command: cd /harness/SmallestSpringApp && mvn clean test
              - step:
                  type: Run
                  name: Code Quality - SonarQube
                  identifier: Code_Quality_SonarQube
                  spec:
                    connectorRef: first_Docker
                    image: sonarsource/sonar-scanner-cli:latest
                    shell: Sh
                    command: sonar-scanner -Dsonar.projectKey=shankarreddy1219_Smallest-spring-boot-sample -Dsonar.organization=shankarreddy1219 -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_TOKEN -Dsonar.sources=/harness/SmallestSpringApp/src
                    envVariables:
                      SONAR_TOKEN: <+secrets.getValue("sonar_token")>
              - step:
                  type: BuildAndPushDockerRegistry
                  name: Build and Push
                  identifier: Build_and_Push
                  spec:
                    connectorRef: first_Docker
                    repo: shankar1219/harness
                    tags:
                      - latest
                    caching: false
                    dockerfile: SmallestSpringApp/Dockerfile
                    context: SmallestSpringApp
              - step:
                  type: Run
                  name: Trivy Image Scan
                  identifier: Trivy_Image_Scan
                  spec:
                    connectorRef: first_Docker
                    image: aquasec/trivy:latest
                    shell: Sh
                    command: trivy image --exit-code 0 --severity HIGH,CRITICAL --no-progress shankar1219/harness:latest
