pipeline:
  name: my-first-pipeline
  identifier: myfirstpipeline
  projectIdentifier: myfirstci
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: first_git
        repoName: Smallest-spring-boot-sample
        build: <+input>
  stages:
    - stage:
        name: Build
        identifier: Build
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: false
            override: false
            paths: []
          buildIntelligence:
            enabled: false
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Run Tests
                  identifier: Run_Tests
                  spec:
                    connectorRef: first_Docker
                    image: maven:3.9.6-eclipse-temurin-17
                    shell: Bash
                    command: cd /harness/SmallestSpringApp && mvn clean test
              - step:
                  type: Run
                  name: Code Quality - SonarQube
                  identifier: Code_Quality_SonarQube
                  spec:
                    connectorRef: first_Docker
                    image: sonarsource/sonar-scanner-cli:latest
                    shell: Sh
                    command: sh /harness/SmallestSpringApp/sonar.sh
                    envVariables:
                      SONAR_TOKEN: <+secrets.getValue("sonar_token")>
              - step:
                  type: BuildAndPushDockerRegistry
                  name: Build and Push
                  identifier: Build_and_Push
                  spec:
                    connectorRef: first_Docker
                    repo: shankar1219/harness
                    tags:
                      - latest
                    caching: false
                    dockerfile: SmallestSpringApp/Dockerfile
                    context: SmallestSpringApp
              - step:
                  type: Run
                  name: Trivy Image Scan
                  identifier: Trivy_Image_Scan
                  spec:
                    connectorRef: first_Docker
                    image: aquasec/trivy:latest
                    shell: Sh
                    command: trivy image --exit-code 0 --severity HIGH,CRITICAL --no-progress shankar1219/harness:latest
    - stage:
        name: Deploy to Minikube
        identifier: Deploy_to_Minikube
        description: ""
        type: Deployment
        spec:
          deploymentType: Kubernetes
          service:
            serviceRef: springbootapp
          environment:
            environmentRef: minikubedev
            deployToAll: false
            infrastructureDefinitions:
              - identifier: minikubeinfra
          execution:
            steps:
              - step:
                  type: K8sBlueGreenDeploy
                  name: Blue Green Deploy
                  identifier: Blue_Green_Deploy
                  spec:
                    skipDryRun: false
                    pruningEnabled: false
                    skipUnchangedManifest: false
                  timeout: 10m
              - step:
                  type: K8sBGSwapServices
                  name: Swap Services
                  identifier: Swap_Services
                  spec: {}
                  timeout: 10m
            rollbackSteps:
              - step:
                  type: K8sRollingRollback
                  name: K8sRollingRollback_1
                  identifier: K8sRollingRollback_1
                  spec: {}
                  timeout: 10m
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
